# Generated by Django 3.2 on 2023-04-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_title_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
