# Generated by Django 3.2 on 2023-04-19 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, 'Минимальный год : 1')], verbose_name='Год публикации'),
        ),
    ]
