# Generated by Django 3.2 on 2023-04-19 09:02

import django.core.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, 'Минимальный год : 1'), reviews.models.validate_year], verbose_name='Год публикации'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__gt=2023), name='year_cannot_be_in_future'),
        ),
    ]
