# Generated by Django 3.2 on 2023-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230419_0902'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_cannot_be_in_future',
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__lt=2023), name='year_cannot_be_in_future'),
        ),
    ]
